#!/bin/bash

# Author: Onur Bilgin
# Date Created: 07/06/2024
# Last Modified: 07/06/2024

# Description
# Prints "Welcome to bash" to the terminal

# Usage
# first_script

echo "Welcome to bash"
exit 0