#!/opt/homebrew/bin/bash

x=4
y=2
z=3

# echo $(( $x + $y )) You can remove $ sign

echo $(( x + y ))
echo $(( x - y ))
echo $(( x * y ))
echo $(( x / y ))
echo $(( x ** y )) # Power operator
echo $(( x % z )) # Modular operator
echo "scale=2; 5/2" | bc
echo "5^2" | bc # Power operator is different with bc

exit 0